import { Project, ProjectCategory, Task, ExternalCommitment, AtRiskItem, ChatMessage } from './types';

export const INITIAL_CATEGORIES: ProjectCategory[] = [
  {
    id: 'area-career',
    name: 'Career',
    icon: '💼',
    color: '#2563EB',
    badgeLetter: 'C',
    description: 'Target agency outreach, engineering clients, and career trajectory',
  },
  {
    id: 'area-magneto',
    name: 'Magneto',
    icon: '🧲',
    color: '#059669',
    badgeLetter: 'M',
    description: 'Agency client engagements, outbound pipeline, and marketing solutions',
  },
  {
    id: 'area-shamanicca',
    name: 'Shamanicca',
    icon: '🌿',
    color: '#7C3AED',
    badgeLetter: 'S',
    description: 'E-commerce platform, audio production, and ceremonial blends',
  },
  {
    id: 'area-finances',
    name: 'Finances',
    icon: '💰',
    color: '#D97706',
    badgeLetter: 'F',
    description: 'Taxes, cash flow, debt payments, and financial planning',
  },
  {
    id: 'area-health-soul',
    name: 'Health & Soul',
    icon: '🌱',
    color: '#10B981',
    badgeLetter: 'H',
    description: 'Mindfulness, habit tracking, physical recovery, and personal routines',
  },
  {
    id: 'area-reference',
    name: 'Reference',
    icon: '📚',
    color: '#64748B',
    badgeLetter: 'R',
    description: 'Standard operating procedures, documentation, and archival notes',
  },
  {
    id: 'area-personal',
    name: 'Personal',
    icon: '🏠',
    color: '#8B5CF6',
    badgeLetter: 'P',
    description: 'Montreal housing search, creative studio Anormal, and personal life',
  },
];

export const INITIAL_PROJECTS: Project[] = [
  // --- Health & Soul ---
  {
    id: 'proj-bullet-journal-2026',
    name: 'Bullet Journal 2026',
    client: 'Mau Bayuelo',
    scope: '2026 yearly roadmap, quarterly sprints, focus areas and routines',
    area: 'Health & Soul',
    categoryId: 'area-health-soul',
    categoryName: 'Health & Soul',
    color: '#10B981',
    starred: true,
    lastViewedAt: '2026-09-05T15:30:00Z',
    createdAt: '2026-01-01',
  },

  // --- Personal ---
  {
    id: 'proj-montreal',
    name: 'Montreal — Búsqueda Coop Habitación 2027',
    client: 'Personal Life',
    scope: 'Housing cooperative applications, budget tracking, and lease timeline',
    area: 'Personal',
    categoryId: 'area-personal',
    categoryName: 'Personal',
    color: '#8B5CF6',
    starred: false,
    lastViewedAt: '2026-09-03T11:00:00Z',
    createdAt: '2026-05-20',
  },
  {
    id: 'proj-anormal',
    name: 'Anormal',
    client: 'Anormal Studio',
    scope: 'Experimental audio-visual design, creative direction, and identity artifacts',
    area: 'Personal',
    categoryId: 'area-personal',
    categoryName: 'Personal',
    color: '#475569',
    starred: true,
    lastViewedAt: '2026-09-05T16:20:00Z',
    createdAt: '2026-03-10',
    startAt: '2026-09-05T08:00:00Z',
    dueAt: '2026-09-30T17:00:00Z',
    hasCollision: false,
  },
  {
    id: 'proj-viaje-colombia',
    name: 'Viaje a Colombia ❤️',
    client: 'Personal & Family',
    scope: 'Itinerary planning, flight bookings, family visits in Medellín & Bogotá',
    area: 'Personal',
    categoryId: 'area-personal',
    categoryName: 'Personal',
    color: '#0284C7',
    starred: false,
    lastViewedAt: '2026-09-04T12:00:00Z',
    createdAt: '2026-06-15',
  },

  // --- Career ---
  {
    id: 'proj-webdev-job',
    name: 'Get A Web Dev Job',
    client: 'Career & Growth',
    scope: 'Target agency outreach, portfolio refinement, technical interview prep',
    area: 'Career',
    categoryId: 'area-career',
    categoryName: 'Career',
    color: '#2563EB',
    starred: false,
    lastViewedAt: '2026-09-05T13:00:00Z',
    createdAt: '2026-02-15',
    startAt: '2026-09-01T08:00:00Z',
    dueAt: '2026-09-24T17:00:00Z',
    hasCollision: false,
  },
  {
    id: 'proj-dangel',
    name: 'Dangel Therapist — Landing Page',
    client: 'Dangel Therapy',
    scope: 'High-conversion booking landing page, client scheduling, and brand identity',
    area: 'Career',
    categoryId: 'area-career',
    categoryName: 'Career',
    color: '#1D4ED8',
    starred: false,
    lastViewedAt: '2026-09-05T14:15:00Z',
    createdAt: '2026-04-12',
    startAt: '2026-09-01T08:00:00Z',
    dueAt: '2026-09-18T17:00:00Z',
    hasCollision: false,
  },
  {
    id: 'proj-gabby',
    name: 'Portfolio Curation & Showcase',
    client: 'Gabby Creative',
    scope: 'Brand consulting, portfolio curation, and digital showcase',
    area: 'Career',
    categoryId: 'area-career',
    categoryName: 'Career',
    color: '#1D4ED8',
    starred: false,
    lastViewedAt: '2026-09-05T13:40:00Z',
    createdAt: '2026-07-01',
    startAt: '2026-09-01T08:00:00Z',
    dueAt: '2026-09-20T17:00:00Z',
    hasCollision: false,
  },
  {
    id: 'proj-trepied',
    name: 'TrePied — Landing Page',
    client: 'TrePied Architecture',
    scope: 'Portfolio showcase, CMS project updates, and client portal handover',
    area: 'Career',
    categoryId: 'area-career',
    categoryName: 'Career',
    color: '#1D4ED8',
    starred: false,
    lastViewedAt: '2026-09-04T16:00:00Z',
    createdAt: '2026-03-25',
    startAt: '2026-09-01T08:00:00Z',
    dueAt: '2026-09-21T17:00:00Z',
    hasCollision: false,
  },
  {
    id: 'proj-komorebi',
    name: 'Komorebi Tea — Ecommerce & Landing',
    client: 'Komorebi Botanicals Ltd',
    scope: 'Headless Shopify frontend, cart drawer, tasting notes filter',
    area: 'Career',
    categoryId: 'area-career',
    categoryName: 'Career',
    color: '#059669',
    starred: false,
    lastViewedAt: '2026-08-30T14:00:00Z',
    createdAt: '2026-06-20',
    startAt: '2026-09-01T08:00:00Z',
    dueAt: '2026-09-14T17:00:00Z',
    hasCollision: true,
  },
  {
    id: 'proj-sonder',
    name: 'Sonder Film Co. — Production Portfolio',
    client: 'Sonder Cinematic Arts',
    scope: 'Custom WebGL reel scrubber, video grid layout, client review portal',
    area: 'Career',
    categoryId: 'area-career',
    categoryName: 'Career',
    color: '#4338CA',
    starred: false,
    lastViewedAt: '2026-08-25T11:00:00Z',
    createdAt: '2026-07-10',
    startAt: '2026-09-01T08:00:00Z',
    dueAt: '2026-09-16T17:00:00Z',
    hasCollision: true,
  },
  {
    id: 'proj-stillness',
    name: 'Stillness App — Editorial & Audio CMS',
    client: 'Stillness Studio NYC',
    scope: 'Web audio API player, guided meditation session log, Sanity studio schemas',
    area: 'Career',
    categoryId: 'area-career',
    categoryName: 'Career',
    color: '#475569',
    starred: false,
    lastViewedAt: '2026-08-20T17:00:00Z',
    createdAt: '2026-05-14',
    startAt: '2026-09-02T08:00:00Z',
    dueAt: '2026-09-19T17:00:00Z',
    hasCollision: false,
  },

  // --- Magneto ---
  {
    id: 'proj-magneto-pivot',
    name: 'Magneto Mktng',
    client: 'Magneto Media',
    scope: 'Niche positioning, service packaging, and outbound pipeline for AI agents',
    area: 'Magneto',
    categoryId: 'area-magneto',
    categoryName: 'Magneto',
    color: '#059669',
    starred: true,
    lastViewedAt: '2026-09-05T16:45:00Z',
    createdAt: '2026-02-01',
    startAt: '2026-09-01T08:00:00Z',
    dueAt: '2026-09-25T17:00:00Z',
    hasCollision: false,
  },
  {
    id: 'proj-jitani',
    name: 'KinoLibelula — Landing Page',
    client: 'Jitani',
    scope: 'Catalog architecture, lookbook gallery, and e-commerce checkout flow',
    area: 'Magneto',
    categoryId: 'area-magneto',
    categoryName: 'Magneto',
    color: '#059669',
    starred: false,
    lastViewedAt: '2026-09-02T10:00:00Z',
    createdAt: '2026-05-01',
    startAt: '2026-09-03T08:00:00Z',
    dueAt: '2026-09-22T17:00:00Z',
    hasCollision: false,
  },
  {
    id: 'proj-kio',
    name: 'Kio',
    client: 'Kio Vending Solutions',
    scope: 'Interactive machine locator, maintenance tickets, route planning',
    area: 'Magneto',
    categoryId: 'area-magneto',
    categoryName: 'Magneto',
    color: '#059669',
    starred: false,
    lastViewedAt: '2026-09-01T09:00:00Z',
    createdAt: '2026-06-01',
    startAt: '2026-09-04T08:00:00Z',
    dueAt: '2026-09-28T17:00:00Z',
    hasCollision: false,
  },

  // --- Shamanicca ---
  {
    id: 'proj-shamanicca-ecom',
    name: 'Shamanicca',
    client: 'Shamanicca Studios',
    scope: 'Ceremonial herbal blends, content engine, and e-commerce platform',
    area: 'Shamanicca',
    categoryId: 'area-shamanicca',
    categoryName: 'Shamanicca',
    color: '#7C3AED',
    starred: true,
    lastViewedAt: '2026-09-05T17:00:00Z',
    createdAt: '2026-01-10',
    startAt: '2026-09-01T08:00:00Z',
    dueAt: '2026-09-29T17:00:00Z',
    hasCollision: false,
  },
];

export const INITIAL_COMMITMENTS: ExternalCommitment[] = [
  {
    id: 'comm-mon-shift',
    title: 'Retail Shift — Early Receive & Backstock',
    subline: 'Westport Provisions',
    day: 'Mon',
    startTime: '06:30',
    endTime: '11:45',
    durationDisplay: '5h15',
    location: 'Westport Provisions — Bay 3',
  },
  {
    id: 'comm-tue-apt',
    title: 'Physiotherapy & Ergonomics Assessment',
    subline: 'Dr. Halpert Clinic',
    day: 'Tue',
    startTime: '09:00',
    endTime: '10:15',
    durationDisplay: '1h15',
    location: 'Suite 402, 14th Ave Medical',
  },
  {
    id: 'comm-wed-shift',
    title: 'Retail Shift — Mid-Day Floor Lead',
    subline: 'Westport Provisions',
    day: 'Wed',
    startTime: '11:00',
    endTime: '16:30',
    durationDisplay: '5h30',
    location: 'Westport Provisions — Front Floor',
  },
  {
    id: 'comm-fri-shift',
    title: 'Retail Shift — Merchandising & Inventory',
    subline: 'Westport Provisions',
    day: 'Fri',
    startTime: '07:00',
    endTime: '12:45',
    durationDisplay: '5h45',
    location: 'Westport Provisions — Main St',
  },
  {
    id: 'comm-sun-shift',
    title: 'Retail Shift — Weekend Close & Safe Audit',
    subline: 'Westport Provisions',
    day: 'Sun',
    startTime: '14:30',
    endTime: '21:15',
    durationDisplay: '6h45',
    location: 'Westport Provisions — Registers & Safe',
  },
];

export const INITIAL_TASKS: Task[] = [
  // --- Completed Tasks (Total 840 min = 14h) ---
  {
    id: 'task-dangel-meeting',
    projectId: 'proj-dangel',
    projectName: 'Dangel Therapist — Landing Page',
    title: 'Dangel — Planificar/asistir reunion de alineación',
    description: 'Reunión de alineación con el cliente para definir entrega final y cronograma.',
    durationMinutes: 60,
    durationDisplay: '1h',
    column: 'done',
    area: 'Magneto',
    priority: 'P2',
    priorityLabel: 'Important',
    energy: 'Medium',
    notes: 'Scope and timeline confirmed with client.',
    subtasks: [],
  },
  {
    id: 'task-dangel-adjustments',
    projectId: 'proj-dangel',
    projectName: 'Dangel Therapist — Landing Page',
    title: 'Dangel — Hacer ajustes del diseño aprobado',
    description: 'Ajustes finales de espaciado y tipografía en Figma antes del corte a código.',
    durationMinutes: 60,
    durationDisplay: '1h',
    column: 'done',
    area: 'Magneto',
    priority: 'P2',
    priorityLabel: 'Normal',
    energy: 'Medium',
    notes: 'Ajustes menores aprobados por el cliente.',
    subtasks: [],
  },
  {
    id: 'task-fin-tax',
    projectId: 'proj-montreal',
    projectName: 'Montreal — Búsqueda Coop Habitación 2027',
    title: 'Verify government tax debt payments & CRA schedule',
    description: 'Verificación de estados de cuenta y comprobantes tributarios para el expediente coop.',
    durationMinutes: 60,
    durationDisplay: '1h',
    column: 'done',
    area: 'Finances',
    priority: 'P1',
    priorityLabel: 'Urgent',
    energy: 'Low',
    tags: ['Money/Admin'],
    notes: 'CRA account verified and monthly installment schedule confirmed.',
    subtasks: [],
  },
  {
    id: 'task-k-seo',
    projectId: 'proj-komorebi',
    projectName: 'Komorebi Tea — Ecommerce & Landing',
    title: 'JSON-LD schema structured data for organic tea cultivars',
    description: 'Add Product and Offer schema markup with batch numbers and harvest elevation fields.',
    durationMinutes: 120,
    durationDisplay: '2h',
    column: 'done',
    area: 'SEO / Meta',
    priority: 'P3',
    energy: 'Low',
    dueDate: 'Wed, Sep 2',
    subtasks: [
      { id: 'sub-81', title: 'Validate schema via Google Rich Results test', completed: true },
    ],
  },
  {
    id: 'task-k-handoff-assets',
    projectId: 'proj-komorebi',
    projectName: 'Komorebi Tea — Ecommerce & Landing',
    title: 'Packaging print cut-line SVG export pipeline',
    description: 'Package high-res vector graphics and rasterized ingredient labels for print run in Kyoto.',
    durationMinutes: 60,
    durationDisplay: '1h',
    column: 'done',
    area: 'Production',
    priority: 'P2',
    energy: 'Medium',
    dueDate: 'Sun, Sep 13',
    subtasks: [
      { id: 'sub-91', title: 'Deliver Figma asset bundle and Pantone mapping', completed: true },
    ],
  },
  {
    id: 'task-s-client-portal',
    projectId: 'proj-sonder',
    projectName: 'Sonder Film Co. — Production Portfolio',
    title: 'Password protected rough-cut screening link generator',
    description: 'Expiring tokenized links for private producer review with watermark overlay.',
    durationMinutes: 180,
    durationDisplay: '3h',
    column: 'done',
    area: 'Security',
    priority: 'P1',
    energy: 'Deep',
    dueDate: 'Tue, Sep 1',
    subtasks: [
      { id: 'sub-141', title: 'Generate HMAC signature for video stream URL', completed: true },
    ],
  },
  {
    id: 'task-s-staging-dns',
    projectId: 'proj-sonder',
    projectName: 'Sonder Film Co. — Production Portfolio',
    title: 'Production SSL migration and CDN edge cache invalidation rule',
    description: 'Point apex domain to Cloudflare edge and configure aggressive asset caching for media streams.',
    durationMinutes: 60,
    durationDisplay: '1h',
    column: 'done',
    area: 'DevOps / CDN',
    priority: 'P1',
    energy: 'Low',
    dueDate: 'Mon, Sep 7',
    subtasks: [
      { id: 'sub-151', title: 'Configure cache purge webhook in GitHub Actions', completed: true },
    ],
  },
  {
    id: 'task-m-export-hls',
    projectId: 'proj-stillness',
    projectName: 'Stillness App — Editorial & Audio CMS',
    title: 'Automated HLS audio stream transcode pipeline test',
    description: 'Verify 64kbps, 128kbps, and 256kbps AAC audio streams play smoothly over throttled 3G cellular.',
    durationMinutes: 180,
    durationDisplay: '3h',
    column: 'done',
    area: 'Media / Infra',
    priority: 'P2',
    energy: 'Medium',
    dueDate: 'Sun, Aug 30',
    subtasks: [
      { id: 'sub-191', title: 'Set up ffmpeg segment manifest parser', completed: true },
    ],
  },
  {
    id: 'task-m-client-walkthrough',
    projectId: 'proj-stillness',
    projectName: 'Stillness App — Editorial & Audio CMS',
    title: 'Sanity Studio editor walkthrough with head instructor',
    description: 'Walk Maya through track uploading, tag assignment, and schedule previewing.',
    durationMinutes: 60,
    durationDisplay: '1h',
    column: 'done',
    area: 'Client / Training',
    priority: 'P2',
    energy: 'Medium',
    dueDate: 'Thu, Sep 10',
    subtasks: [
      { id: 'sub-201', title: 'Record 8-minute Loom walkthrough for editorial staff', completed: true },
    ],
  },

  // --- Active & Queued Tasks (Total 1020 min = 17h) ---
  // Today's primary task (Current work block)
  {
    id: 'task-k-checkout',
    projectId: 'proj-komorebi',
    projectName: 'Komorebi Tea — Ecommerce & Landing',
    title: 'Refactor checkout drawer state & cart bundle calculation',
    description: 'Fix bundle discount calculation edge case when 3-pack matcha tin is mixed with loose leaf pouch. Verify currency conversion persists in storage.',
    durationMinutes: 130,
    durationDisplay: '2h10',
    column: 'in_progress',
    area: 'Checkout / State',
    priority: 'P1',
    energy: 'Deep',
    scheduledDay: 'Fri',
    scheduledStart: '13:45',
    scheduledEnd: '15:55',
    dueDate: 'Today, 18:00',
    isToday: true,
    subtasks: [
      { id: 'sub-1', title: 'Isolate discount multiplier utility function', completed: true },
      { id: 'sub-2', title: 'Handle empty tea strainer edge case in cart drawer', completed: true },
      { id: 'sub-3', title: 'Verify unit test suite with currency formatter', completed: false },
      { id: 'sub-4', title: 'Cross-browser check on iOS Safari 17 mobile viewport', completed: false },
    ],
    notes: 'Client reviewed invoice yesterday. Need clean staging deploy by 17:00 before weekend campaign rollout.',
  },
  // Today's secondary tasks (Next up / Rest of day)
  {
    id: 'task-s-webgl',
    projectId: 'proj-sonder',
    projectName: 'Sonder Film Co. — Production Portfolio',
    title: 'Optimize WebGL reel scrub physics & pointer velocity',
    description: 'Smooth damping friction on mouse wheel scrub for high refresh monitors. Prevent stutter when switching 4K thumbnail previews.',
    durationMinutes: 47,
    durationDisplay: '47 min',
    column: 'todo',
    area: 'WebGL / Motion',
    priority: 'P2',
    energy: 'Deep',
    scheduledDay: 'Fri',
    scheduledStart: '16:15',
    scheduledEnd: '17:02',
    dueDate: 'Today, 19:30',
    isToday: true,
    subtasks: [
      { id: 'sub-21', title: 'Calculate delta smoothing coefficient', completed: true },
      { id: 'sub-22', title: 'Throttle requestAnimationFrame dispatch', completed: false },
    ],
  },
  {
    id: 'task-m-audio',
    projectId: 'proj-stillness',
    projectName: 'Stillness App — Editorial & Audio CMS',
    title: 'Audio streaming chunk cache fallback for offline play',
    description: 'Implement indexedDB segment buffer caching for 20-minute bell meditations so audio does not stutter in airplane mode.',
    durationMinutes: 85,
    durationDisplay: '1h25',
    column: 'todo',
    area: 'Web Audio API',
    priority: 'P2',
    energy: 'Medium',
    scheduledDay: 'Fri',
    scheduledStart: '17:15',
    scheduledEnd: '18:40',
    dueDate: 'Today, 21:00',
    isToday: true,
    subtasks: [
      { id: 'sub-31', title: 'Define IDB object store for PCM audio blob chunks', completed: false },
      { id: 'sub-32', title: 'Add offline recovery toast notification', completed: false },
    ],
  },
  // Upcoming ready tasks
  {
    id: 'task-k-brewing',
    projectId: 'proj-komorebi',
    projectName: 'Komorebi Tea — Ecommerce & Landing',
    title: 'Dynamic water temp slider & steeping timer widget',
    description: 'Build responsive SVG thermometer slider with degree conversion and haptic audio tone at end of timer.',
    durationMinutes: 195,
    durationDisplay: '3h15',
    column: 'todo',
    area: 'Components',
    priority: 'P2',
    energy: 'Medium',
    dueDate: 'Thu, Sep 10',
    subtasks: [
      { id: 'sub-41', title: 'Figma specs for temperature ticks', completed: true },
      { id: 'sub-42', title: 'Implement Web Audio oscillator bell', completed: false },
    ],
  },
  // At-risk tasks (Sonder & Komorebi)
  {
    id: 'task-s-scrubber',
    projectId: 'proj-sonder',
    projectName: 'Sonder Film Co. — Production Portfolio',
    title: 'Custom video playback scrubber with frame accurate hover',
    description: 'Hover timeline scrub displays micro-preview thumbnails generated at 1s intervals. Needs performance caching.',
    durationMinutes: 240,
    durationDisplay: '4h00',
    column: 'todo',
    area: 'Video / UI',
    priority: 'P1',
    energy: 'Deep',
    dueDate: 'Fri, Sep 5',
    subtasks: [
      { id: 'sub-101', title: 'Build sprite sheet decoder in Web Worker', completed: false },
      { id: 'sub-102', title: 'Interpolate timestamp mouse coordinates', completed: false },
    ],
  },
  {
    id: 'task-k-webhook',
    projectId: 'proj-komorebi',
    projectName: 'Komorebi Tea — Ecommerce & Landing',
    title: 'Shopify headless webhook sync & error boundary',
    description: 'Verify HMAC signatures from Shopify event stream and build graceful fallback state for out-of-stock variations.',
    durationMinutes: 195,
    durationDisplay: '3h15',
    column: 'todo',
    area: 'Backend',
    priority: 'P1',
    energy: 'Deep',
    dueDate: 'Thu, Sep 4',
    subtasks: [
      { id: 'sub-61', title: 'HMAC signature verification middleware', completed: true },
      { id: 'sub-62', title: 'Dead letter queue retry handler', completed: false },
    ],
  },
  {
    id: 'task-m-binaural',
    projectId: 'proj-stillness',
    projectName: 'Stillness App — Editorial & Audio CMS',
    title: 'Binaural beat oscillator frequency pairing generator',
    description: 'Generate 432Hz theta waves with exact carrier and offset frequencies using Web Audio API nodes.',
    durationMinutes: 128,
    durationDisplay: '2h08',
    column: 'todo',
    area: 'Audio Synthesis',
    priority: 'P1',
    energy: 'Deep',
    dueDate: 'Sat, Sep 6',
    subtasks: [
      { id: 'sub-161', title: 'Calibrate StereoPannerNode channel separation', completed: false },
      { id: 'sub-162', title: 'Add gradual fade-in gain envelope over 12 seconds', completed: false },
    ],
  },
  // Additional tasks for projects so each calculates its own standing
  {
    id: 'task-kl-lookbook',
    projectId: 'proj-jitani',
    projectName: 'KinoLibelula — Landing Page',
    title: 'Lookbook responsive masonry gallery & lightbox',
    description: 'Build touch-friendly full-screen lookbook zoom for high-res apparel campaign photography.',
    durationMinutes: 120,
    durationDisplay: '2h',
    column: 'done',
    area: 'Frontend',
    priority: 'P2',
    energy: 'Medium',
    dueDate: 'Mon, Sep 7',
    subtasks: [],
    notes: 'Approved by Jitani team during Tuesday review.',
  },
  {
    id: 'task-kl-checkout',
    projectId: 'proj-jitani',
    projectName: 'KinoLibelula — Landing Page',
    title: 'Stripe Elements embedded checkout & tax calculator',
    description: 'Integrate dynamic postal code tax calculation and Apple Pay payment request button.',
    durationMinutes: 150,
    durationDisplay: '2h30',
    column: 'todo',
    area: 'Payments',
    priority: 'P1',
    energy: 'Deep',
    dueDate: 'Sun, Sep 13',
    subtasks: [],
    notes: 'Needs sandbox webhook listener verified.',
  },
  {
    id: 'task-tr-review',
    projectId: 'proj-trepied',
    projectName: 'TrePied — Landing Page',
    title: 'TrePied architectural layout review & Figma tokens',
    description: 'Export SVG elevation blueprints and standardize grid spacing across project pages.',
    durationMinutes: 90,
    durationDisplay: '1h30',
    column: 'done',
    area: 'Design QA',
    priority: 'P2',
    energy: 'Medium',
    subtasks: [],
  },
  {
    id: 'task-tr-cms',
    projectId: 'proj-trepied',
    projectName: 'TrePied — Landing Page',
    title: 'Sanity CMS portfolio project schemas & video embed',
    description: 'Configure multi-image carousel blocks and client quote callouts.',
    durationMinutes: 120,
    durationDisplay: '2h',
    column: 'todo',
    area: 'CMS / Backend',
    priority: 'P2',
    energy: 'Medium',
    dueDate: 'Wed, Sep 16',
    subtasks: [],
  },
  {
    id: 'task-mag-analysis',
    projectId: 'proj-magneto-pivot',
    projectName: 'Magneto Mktng',
    title: 'Competitive analysis of AI agency offerings & tier pricing',
    description: 'Synthesize pricing patterns across 8 boutique automation consultancies.',
    durationMinutes: 90,
    durationDisplay: '1h30',
    column: 'done',
    area: 'Strategy',
    priority: 'P2',
    energy: 'Low',
    subtasks: [],
  },
  {
    id: 'task-mag-pitch',
    projectId: 'proj-magneto-pivot',
    projectName: 'Magneto Mktng',
    title: 'Niche positioning & service packaging blueprint',
    description: 'Draft 3 core packaged agency offers for SMB lead qualification agents.',
    durationMinutes: 180,
    durationDisplay: '3h',
    column: 'todo',
    area: 'Strategy',
    priority: 'P1',
    energy: 'Deep',
    dueDate: 'Fri, Sep 18',
    subtasks: [],
  },
  {
    id: 'task-sh-taxonomy',
    projectId: 'proj-shamanicca-ecom',
    projectName: 'Shamanicca',
    title: 'E-commerce taxonomy for botanical blends & rituals',
    description: 'Structure categories, herbs, and sensory profile filters.',
    durationMinutes: 60,
    durationDisplay: '1h',
    column: 'done',
    area: 'Information Arch',
    priority: 'P3',
    energy: 'Low',
    subtasks: [],
  },
  {
    id: 'task-sh-catalog',
    projectId: 'proj-shamanicca-ecom',
    projectName: 'Shamanicca',
    title: 'Product detail page sticky add-to-cart drawer',
    description: 'Implement bundle discount tier indicator and subscription toggle.',
    durationMinutes: 120,
    durationDisplay: '2h',
    column: 'todo',
    area: 'Frontend',
    priority: 'P2',
    energy: 'Medium',
    dueDate: 'Mon, Sep 21',
    subtasks: [],
  },
  {
    id: 'task-an-assets',
    projectId: 'proj-anormal',
    projectName: 'Anormal',
    title: 'Audio-visual design assets packaging & vector marks',
    description: 'Optimize WebGL particle canvas textures and SVG branding marks.',
    durationMinutes: 90,
    durationDisplay: '1h30',
    column: 'done',
    area: 'Design QA',
    priority: 'P2',
    energy: 'Medium',
    subtasks: [],
  },
  {
    id: 'task-an-prototype',
    projectId: 'proj-anormal',
    projectName: 'Anormal',
    title: 'Interactive 3D distortion canvas experiment',
    description: 'Three.js shader pass for cursor hover displacement effect on hero showcase.',
    durationMinutes: 150,
    durationDisplay: '2h30',
    column: 'todo',
    area: 'Creative Tech',
    priority: 'P2',
    energy: 'Deep',
    dueDate: 'Tue, Sep 15',
    subtasks: [],
  },
  {
    id: 'task-job-cv',
    projectId: 'proj-webdev-job',
    projectName: 'Get A Web Dev Job',
    title: 'Resume & portfolio case study updates with TypeScript projects',
    description: 'Add quantitative metrics for freelance web applications built in 2026.',
    durationMinutes: 60,
    durationDisplay: '1h',
    column: 'done',
    area: 'Career',
    priority: 'P2',
    energy: 'Low',
    subtasks: [],
  },
  {
    id: 'task-job-interview',
    projectId: 'proj-webdev-job',
    projectName: 'Get A Web Dev Job',
    title: 'Technical interview prep: React concurrency & state patterns',
    description: 'Review custom hooks, memoization pitfalls, and server component boundaries.',
    durationMinutes: 120,
    durationDisplay: '2h',
    column: 'todo',
    area: 'Career',
    priority: 'P1',
    energy: 'Deep',
    dueDate: 'Thu, Sep 17',
    subtasks: [],
  },
  {
    id: 'task-bujo-retro',
    projectId: 'proj-bullet-journal-2026',
    projectName: 'Bullet Journal 2026',
    title: 'Q3 retrospective & monthly habit review log',
    description: 'Synthesize monthly shift sleep consistency and freelance project delivery pacing.',
    durationMinutes: 60,
    durationDisplay: '1h',
    column: 'done',
    area: 'Personal Life',
    priority: 'P3',
    energy: 'Low',
    subtasks: [],
  },
  {
    id: 'task-bujo-q4',
    projectId: 'proj-bullet-journal-2026',
    projectName: 'Bullet Journal 2026',
    title: 'Q4 monthly spread layout & capacity budgeting matrix',
    description: 'Map out retail shifts against project milestones for October through December.',
    durationMinutes: 75,
    durationDisplay: '1h15',
    column: 'todo',
    area: 'Personal Life',
    priority: 'P3',
    energy: 'Medium',
    dueDate: 'Sat, Sep 19',
    subtasks: [],
  },
  {
    id: 'task-gb-assets',
    projectId: 'proj-gabby',
    projectName: 'Portfolio Curation & Showcase',
    title: 'Curate project selection & high-res image exports',
    description: 'Select top 6 editorial campaigns and crop for widescreen showcase hero.',
    durationMinutes: 60,
    durationDisplay: '1h',
    column: 'done',
    area: 'Design QA',
    priority: 'P2',
    energy: 'Medium',
    subtasks: [],
  },
  {
    id: 'task-gb-grid',
    projectId: 'proj-gabby',
    projectName: 'Portfolio Curation & Showcase',
    title: 'Digital showcase layout & typography review',
    description: 'Implement fluid typography pairing with editorial serif accents and column grid.',
    durationMinutes: 90,
    durationDisplay: '1h30',
    column: 'todo',
    area: 'Design QA',
    priority: 'P2',
    energy: 'Medium',
    dueDate: 'Sun, Sep 20',
    subtasks: [],
  },
];

export const INITIAL_AT_RISK: AtRiskItem[] = [
  {
    id: 'risk-1',
    taskId: 'task-s-scrubber',
    projectName: 'Sonder Film Co.',
    title: 'Custom video playback scrubber with frame accurate hover',
    shortfall: 'needs 4h, 1h30 available before Fri',
    hoursNeeded: 4.0,
    hoursAvailable: 1.5,
    dueDate: 'Fri, 17:00',
  },
  {
    id: 'risk-2',
    taskId: 'task-k-webhook',
    projectName: 'Komorebi Tea',
    title: 'Shopify headless webhook sync & error boundary',
    shortfall: 'needs 3h15, 45 min available before Thu',
    hoursNeeded: 3.25,
    hoursAvailable: 0.75,
    dueDate: 'Thu, 12:00',
  },
];

export const INITIAL_CHAT_MESSAGES: ChatMessage[] = [
  {
    id: 'msg-coach-consequence',
    sender: 'assistant',
    timestamp: '1:21 pm',
    text: 'The deficit comes from the WebGL task. Cutting it to 17m clears it.',
    actions: [
      {
        label: 'Shorten WebGL physics task from 47m to 17m (clears deficit)',
        type: 'shorten',
        payload: 'task-s-webgl',
      },
      {
        label: 'Reschedule Audio chunk cache to Saturday afternoon',
        type: 'reschedule',
        payload: 'task-m-audio',
      },
      {
        label: 'Keep 5h00 and extend evening window to 7:00 pm',
        type: 'extend',
        payload: 'window',
      },
    ],
  },
];
