import { Project, Task, ExternalCommitment, AtRiskItem, ChatMessage } from './types';

export const INITIAL_PROJECTS: Project[] = [
  {
    id: 'proj-master',
    name: 'Nexus LifeOS — Master Projects',
    client: 'Mau Bayuelo',
    scope: 'Central portfolio of life areas and client projects',
  },
  {
    id: 'proj-agentic',
    name: 'AI Tooling & Agentic Skills',
    client: 'Internal R&D',
    scope: 'Advanced agent workflows, tool orchestration, and LLM integrations',
  },
  {
    id: 'proj-shamanicca-content',
    name: 'Shamanicca Content Engine',
    client: 'Shamanicca Studios',
    scope: 'Multi-channel editorial workflow, audio CMS, and spiritual content pipeline',
  },
  {
    id: 'proj-shamanicca-ecom',
    name: 'Shamanicca eCommerce — Fase 2',
    client: 'Shamanicca Botanica',
    scope: 'Ceremonial herbal blends, cart bundle discounts, and logistics integration',
  },
  {
    id: 'proj-dangel',
    name: 'Dangel Therapist — Landing Page',
    client: 'Dangel Therapy',
    scope: 'High-conversion booking landing page, client scheduling, and brand identity',
  },
  {
    id: 'proj-trepied',
    name: 'TrePied — Landing Page',
    client: 'TrePied Architecture',
    scope: 'Portfolio showcase, CMS project updates, and client portal handover',
  },
  {
    id: 'proj-shamanicca-app',
    name: 'Shamanicca — App Freemium de Meditación',
    client: 'Shamanicca Labs',
    scope: 'Freemium meditation audio app with binaural soundscapes and offline caching',
  },
  {
    id: 'proj-magneto-pivot',
    name: 'Magneto — Exploración de pivote a AI Agency',
    client: 'Magneto Media',
    scope: 'Niche positioning, service packaging, and outbound pipeline for AI agents',
  },
  {
    id: 'proj-montreal',
    name: 'Montreal — Búsqueda Coop Habitación 2027',
    client: 'Personal Life',
    scope: 'Housing cooperative applications, budget tracking, and lease timeline',
  },
  {
    id: 'proj-komorebi',
    name: 'Komorebi Tea — Ecommerce & Landing',
    client: 'Komorebi Botanicals Ltd',
    scope: 'Headless Shopify frontend, cart drawer, tasting notes filter, dynamic brewing guides',
  },
  {
    id: 'proj-sonder',
    name: 'Sonder Film Co. — Production Portfolio',
    client: 'Sonder Cinematic Arts',
    scope: 'Custom WebGL reel scrubber, video grid layout, client review portal, archival index',
  },
  {
    id: 'proj-stillness',
    name: 'Stillness App — Editorial & Audio CMS',
    client: 'Stillness Studio NYC',
    scope: 'Web audio API player, guided meditation session log, Sanity studio schemas',
  },
];

export const INITIAL_COMMITMENTS: ExternalCommitment[] = [
  {
    id: 'comm-mon-shift',
    title: 'Retail Shift — Early Receive & Backstock',
    subline: 'Westport Provisions',
    day: 'Mon',
    startTime: '06:30',
    endTime: '11:45',
    durationDisplay: '5h15',
    location: 'Westport Provisions — Bay 3',
  },
  {
    id: 'comm-tue-apt',
    title: 'Physiotherapy & Ergonomics Assessment',
    subline: 'Dr. Halpert Clinic',
    day: 'Tue',
    startTime: '09:00',
    endTime: '10:15',
    durationDisplay: '1h15',
    location: 'Suite 402, 14th Ave Medical',
  },
  {
    id: 'comm-wed-shift',
    title: 'Retail Shift — Mid-Day Floor Lead',
    subline: 'Westport Provisions',
    day: 'Wed',
    startTime: '11:00',
    endTime: '16:30',
    durationDisplay: '5h30',
    location: 'Westport Provisions — Front Floor',
  },
  {
    id: 'comm-fri-shift',
    title: 'Retail Shift — Merchandising & Inventory',
    subline: 'Westport Provisions',
    day: 'Fri',
    startTime: '07:00',
    endTime: '12:45',
    durationDisplay: '5h45',
    location: 'Westport Provisions — Main St',
  },
  {
    id: 'comm-sun-shift',
    title: 'Retail Shift — Weekend Close & Safe Audit',
    subline: 'Westport Provisions',
    day: 'Sun',
    startTime: '14:30',
    endTime: '21:15',
    durationDisplay: '6h45',
    location: 'Westport Provisions — Registers & Safe',
  },
];

export const INITIAL_TASKS: Task[] = [
  // Nexus LifeOS Master Tasks (From screenshot)
  {
    id: 'task-magneto-niches',
    projectId: 'proj-magneto-pivot',
    projectName: 'Magneto — Exploración de pivote a AI Agency',
    title: 'Magneto — Business Niches + Positioning',
    description: 'Evaluate high-value agency niches, define service offerings (agentic automations, content pipelines), and establish dual-language client acquisition funnels.',
    durationMinutes: 90,
    durationDisplay: '1h30',
    column: 'waiting',
    area: 'Magneto',
    priority: 'P2',
    priorityLabel: 'Important',
    energy: 'Empty',
    isMilestone: false,
    dueDate: '',
    notes: 'Target niches: Wellness/spirituality brands, eCommerce, coaches, bilingual markets (EN/ES).',
    projectRelation: 'Magneto — Exploración de pivote a AI Agency',
    tags: ['AI Agency', 'Strategy'],
    subtasks: [
      { id: 'sub-mag-1', title: 'Compile competitor pricing grid in wellness/spiritual space', completed: true },
      { id: 'sub-mag-2', title: 'Draft bilingual offer deck (EN/ES)', completed: false },
      { id: 'sub-mag-3', title: 'Schedule 3 discovery calls with boutique agencies', completed: false },
    ],
    comments: [
      {
        id: 'comm-1',
        author: 'Mau Bayuelo',
        initials: 'MB',
        timestamp: 'Yesterday at 4:15 PM',
        text: 'Identified strong overlap with Shamanicca editorial workflows. Can package agentic skills as a core service.',
      },
    ],
  },
  {
    id: 'task-trepied-landing',
    projectId: 'proj-trepied',
    projectName: 'TrePied — Landing Page',
    title: 'TrePied — Actualizar proyectos en landing page',
    description: 'Entrega de accesos admin y tutorial al cliente para actualización autónoma del portafolio.',
    durationMinutes: 45,
    durationDisplay: '45m',
    column: 'cancelled',
    area: 'Magneto',
    priority: 'P3',
    priorityLabel: 'Low',
    energy: 'Low',
    isMilestone: false,
    notes: 'CANCELADO (5 ago 2026) — absorbido por el handoff. Isra no ha manifestado tener información nueva, y la decisión es entregarle acceso admin + tutorial (como con Dangel) para que actualice proyectos él mismo. Si Magneto lo hace, es trabajo gratis recurrente sin fin.',
    projectRelation: 'TrePied — Landing Page',
    subtasks: [],
  },
  {
    id: 'task-kio-site',
    projectId: 'proj-agentic',
    projectName: 'AI Tooling & Agentic Skills',
    title: 'Kio — Desarrollar sitio con info actual (mientras Alejo decide)',
    description: 'Desarrollo de landing estática mientras se define la sociedad y modelo operativo.',
    durationMinutes: 60,
    durationDisplay: '1h',
    column: 'cancelled',
    area: 'Magneto',
    priority: 'P3',
    priorityLabel: 'Low',
    energy: 'Low',
    notes: 'Proyecto Kio cancelado — Alejo no avanzó con los socios de Canadá.',
    projectRelation: 'AI Tooling & Agentic Skills',
    subtasks: [],
  },
  {
    id: 'task-kio-vending',
    projectId: 'proj-agentic',
    projectName: 'AI Tooling & Agentic Skills',
    title: 'Kio / Alejo — Kio Vending Site',
    description: 'Requisitos de backend y POS para máquinas expendedoras inteligentes.',
    durationMinutes: 30,
    durationDisplay: '30m',
    column: 'cancelled',
    area: 'Magneto',
    priority: 'P3',
    priorityLabel: 'Low',
    energy: 'Low',
    notes: 'Reunión exploratoria de arquitectura de quioscos cancelada por pausa del cliente.',
    projectRelation: 'AI Tooling & Agentic Skills',
    subtasks: [],
  },
  {
    id: 'task-dangel-meeting',
    projectId: 'proj-dangel',
    projectName: 'Dangel Therapist — Landing Page',
    title: 'Dangel — Planificar/asistir reunion',
    description: 'Reunión de alineación con el cliente para definir entrega final y cronograma.',
    durationMinutes: 60,
    durationDisplay: '1h',
    column: 'done',
    area: 'Magneto',
    priority: 'P2',
    priorityLabel: 'Important',
    energy: 'Medium',
    notes: 'Reach out to resume work. Clarify scope and timeline.',
    projectRelation: 'Dangel Therapist — Landing Page',
    subtasks: [],
  },
  {
    id: 'task-dangel-adjustments',
    projectId: 'proj-dangel',
    projectName: 'Dangel Therapist — Landing Page',
    title: 'Dangel — Hacer ajustes del diseño aprobado',
    description: 'Ajustes finales de espaciado y tipografía en Figma antes del corte a código.',
    durationMinutes: 75,
    durationDisplay: '1h15',
    column: 'done',
    area: 'Magneto',
    priority: 'P2',
    priorityLabel: 'Normal',
    energy: 'Medium',
    notes: 'Incorporar cualquier ajuste menor del cliente antes de pasar a desarrollo.',
    projectRelation: 'Dangel Therapist — Landing Page',
    subtasks: [],
  },
  {
    id: 'task-fin-tax',
    projectId: 'proj-montreal',
    projectName: 'Montreal — Búsqueda Coop Habitación 2027',
    title: 'Verify government tax debt payments',
    description: 'Verificación de estados de cuenta y comprobantes tributarios para el expediente coop.',
    durationMinutes: 30,
    durationDisplay: '30m',
    column: 'done',
    area: 'Finances',
    priority: 'P1',
    priorityLabel: 'Urgent',
    energy: 'Low',
    tags: ['Money/Admin'],
    notes: 'Check CRA account and verify monthly installment schedule confirmation.',
    projectRelation: 'Montreal — Búsqueda Coop Habitación 2027',
    subtasks: [],
  },
  {
    id: 'task-dangel-dev',
    projectId: 'proj-dangel',
    projectName: 'Dangel Therapist — Landing Page',
    title: 'Dangel — Develop Landing Page',
    description: 'Implement approved design with Framer Motion animations and Cal.com embed.',
    durationMinutes: 180,
    durationDisplay: '3h',
    column: 'todo',
    area: 'Magneto',
    priority: 'P1',
    priorityLabel: 'Urgent',
    energy: 'Deep',
    notes: 'Setup Next.js responsive landing page and Tailwind typography.',
    projectRelation: 'Dangel Therapist — Landing Page',
    subtasks: [],
  },

  // Today's primary task
  {
    id: 'task-k-checkout',
    projectId: 'proj-komorebi',
    projectName: 'Komorebi Tea — Ecommerce & Landing',
    title: 'Refactor checkout drawer state & cart bundle calculation',
    description: 'Fix bundle discount calculation edge case when 3-pack matcha tin is mixed with loose leaf pouch. Verify currency conversion persists in storage.',
    durationMinutes: 130,
    durationDisplay: '2h10',
    column: 'in_progress',
    area: 'Checkout / State',
    priority: 'P1',
    energy: 'Deep',
    scheduledDay: 'Fri',
    scheduledStart: '13:45',
    scheduledEnd: '15:55',
    dueDate: 'Today, 18:00',
    isToday: true,
    subtasks: [
      { id: 'sub-1', title: 'Isolate discount multiplier utility function', completed: true },
      { id: 'sub-2', title: 'Handle empty tea strainer edge case in cart drawer', completed: true },
      { id: 'sub-3', title: 'Verify unit test suite with currency formatter', completed: false },
      { id: 'sub-4', title: 'Cross-browser check on iOS Safari 17 mobile viewport', completed: false },
    ],
    notes: 'Client reviewed invoice yesterday. Need clean staging deploy by 17:00 before weekend campaign rollout.',
  },
  // Today's secondary tasks
  {
    id: 'task-s-webgl',
    projectId: 'proj-sonder',
    projectName: 'Sonder Film Co. — Production Portfolio',
    title: 'Optimize WebGL reel scrub physics & pointer velocity',
    description: 'Smooth damping friction on mouse wheel scrub for high refresh monitors. Prevent stutter when switching 4K thumbnail previews.',
    durationMinutes: 47,
    durationDisplay: '47 min',
    column: 'todo',
    area: 'WebGL / Motion',
    priority: 'P2',
    energy: 'Deep',
    scheduledDay: 'Fri',
    scheduledStart: '16:15',
    scheduledEnd: '17:02',
    dueDate: 'Today, 19:30',
    isToday: true,
    subtasks: [
      { id: 'sub-21', title: 'Calculate delta smoothing coefficient', completed: true },
      { id: 'sub-22', title: 'Throttle requestAnimationFrame dispatch', completed: false },
    ],
  },
  {
    id: 'task-m-audio',
    projectId: 'proj-stillness',
    projectName: 'Stillness App — Editorial & Audio CMS',
    title: 'Audio streaming chunk cache fallback for offline play',
    description: 'Implement indexedDB segment buffer caching for 20-minute bell meditations so audio does not stutter in airplane mode.',
    durationMinutes: 85,
    durationDisplay: '1h25',
    column: 'todo',
    area: 'Web Audio API',
    priority: 'P2',
    energy: 'Medium',
    scheduledDay: 'Fri',
    scheduledStart: '17:15',
    scheduledEnd: '18:40',
    dueDate: 'Today, 21:00',
    isToday: true,
    subtasks: [
      { id: 'sub-31', title: 'Define IDB object store for PCM audio blob chunks', completed: false },
      { id: 'sub-32', title: 'Add offline recovery toast notification', completed: false },
    ],
  },

  // Komorebi Board Tasks
  {
    id: 'task-k-brewing',
    projectId: 'proj-komorebi',
    projectName: 'Komorebi Tea — Ecommerce & Landing',
    title: 'Dynamic water temp slider & steeping timer widget',
    description: 'Build responsive SVG thermometer slider with degree conversion and haptic audio tone at end of timer.',
    durationMinutes: 195,
    durationDisplay: '3h15',
    column: 'backlog',
    area: 'Components',
    priority: 'P2',
    energy: 'Medium',
    dueDate: 'Thu, Sep 10',
    subtasks: [
      { id: 'sub-41', title: 'Figma specs for temperature ticks', completed: true },
      { id: 'sub-42', title: 'Implement Web Audio oscillator bell', completed: false },
    ],
  },
  {
    id: 'task-k-tasting',
    projectId: 'proj-komorebi',
    projectName: 'Komorebi Tea — Ecommerce & Landing',
    title: 'Tasting notes radar chart using SVG math',
    description: 'Multi-axis flavor profile chart (astringency, umami, sweetness, vegetative, roast). Pure SVG calculation with no external charting bloat.',
    durationMinutes: 140,
    durationDisplay: '2h20',
    column: 'todo',
    area: 'Data Vis',
    priority: 'P2',
    energy: 'Deep',
    dueDate: 'Tue, Sep 8',
    subtasks: [
      { id: 'sub-51', title: 'Normalize polygon coordinates to 100x100 viewBox', completed: false },
    ],
  },
  {
    id: 'task-k-webhook',
    projectId: 'proj-komorebi',
    projectName: 'Komorebi Tea — Ecommerce & Landing',
    title: 'Shopify headless webhook sync & error boundary',
    description: 'Handle out-of-stock webhook updates without full page reloads during flash drops.',
    durationMinutes: 195,
    durationDisplay: '3h15',
    column: 'todo',
    area: 'API / Sync',
    priority: 'P1',
    energy: 'Deep',
    dueDate: 'Thu, Sep 10',
    subtasks: [
      { id: 'sub-61', title: 'Write webhook signature verification helper', completed: true },
      { id: 'sub-62', title: 'Simulate concurrent race condition payloads', completed: false },
    ],
  },
  {
    id: 'task-k-typography',
    projectId: 'proj-komorebi',
    projectName: 'Komorebi Tea — Ecommerce & Landing',
    title: 'Vertical Japanese glyph typographic layout review',
    description: 'Verify writing-mode: vertical-rl compatibility with Safari subpixel rendering on harvest dates column.',
    durationMinutes: 55,
    durationDisplay: '55 min',
    column: 'in_review',
    area: 'Typography',
    priority: 'P3',
    energy: 'Low',
    dueDate: 'Mon, Sep 7',
    subtasks: [
      { id: 'sub-71', title: 'Test font-feature-settings: "vpal"', completed: true },
    ],
  },
  {
    id: 'task-k-seo',
    projectId: 'proj-komorebi',
    projectName: 'Komorebi Tea — Ecommerce & Landing',
    title: 'JSON-LD schema structured data for organic tea cultivars',
    description: 'Add Product and Offer schema markup with batch numbers and harvest elevation fields.',
    durationMinutes: 40,
    durationDisplay: '40 min',
    column: 'done',
    area: 'SEO / Meta',
    priority: 'P3',
    energy: 'Low',
    dueDate: 'Wed, Sep 2',
    subtasks: [
      { id: 'sub-81', title: 'Validate schema via Google Rich Results test', completed: true },
    ],
  },
  {
    id: 'task-k-handoff-assets',
    projectId: 'proj-komorebi',
    projectName: 'Komorebi Tea — Ecommerce & Landing',
    title: 'Packaging print cut-line SVG export pipeline',
    description: 'Package high-res vector graphics and rasterized ingredient labels for print run in Kyoto.',
    durationMinutes: 75,
    durationDisplay: '1h15',
    column: 'handoff',
    area: 'Production',
    priority: 'P2',
    energy: 'Medium',
    dueDate: 'Sun, Sep 13',
    subtasks: [
      { id: 'sub-91', title: 'Deliver Figma asset bundle and Pantone mapping', completed: true },
    ],
  },

  // Sonder Board Tasks
  {
    id: 'task-s-scrubber',
    projectId: 'proj-sonder',
    projectName: 'Sonder Film Co. — Production Portfolio',
    title: 'Custom video playback scrubber with frame accurate hover',
    description: 'Hover timeline scrub displays micro-preview thumbnails generated at 1s intervals. Needs performance caching.',
    durationMinutes: 240,
    durationDisplay: '4h00',
    column: 'todo',
    area: 'Video / UI',
    priority: 'P1',
    energy: 'Deep',
    dueDate: 'Fri, Sep 5',
    subtasks: [
      { id: 'sub-101', title: 'Build sprite sheet decoder in Web Worker', completed: false },
      { id: 'sub-102', title: 'Interpolate timestamp mouse coordinates', completed: false },
    ],
  },
  {
    id: 'task-s-archive',
    projectId: 'proj-sonder',
    projectName: 'Sonder Film Co. — Production Portfolio',
    title: 'Director reel archival filter by camera package & aspect ratio',
    description: 'Faceted filtering system (Arri Alexa 35, 16mm Bolex, Anamorphic 2.39:1). Instant client-side state transition.',
    durationMinutes: 110,
    durationDisplay: '1h50',
    column: 'backlog',
    area: 'Architecture',
    priority: 'P2',
    energy: 'Medium',
    dueDate: 'Wed, Sep 9',
    subtasks: [
      { id: 'sub-111', title: 'Create query parameter synchronization hook', completed: false },
    ],
  },
  {
    id: 'task-s-presskit',
    projectId: 'proj-sonder',
    projectName: 'Sonder Film Co. — Production Portfolio',
    title: 'Festival laurels SVG generator & press asset ZIP builder',
    description: 'Dynamic serverless endpoint for bundling official laurels into print-ready SVG packages for Sundance submission.',
    durationMinutes: 95,
    durationDisplay: '1h35',
    column: 'in_progress',
    area: 'Backend / Zip',
    priority: 'P2',
    energy: 'Medium',
    dueDate: 'Sat, Sep 6',
    subtasks: [
      { id: 'sub-121', title: 'Build laurel branch geometric path generator', completed: true },
      { id: 'sub-122', title: 'Test streaming ZIP response', completed: false },
    ],
  },
  {
    id: 'task-s-case-study',
    projectId: 'proj-sonder',
    projectName: 'Sonder Film Co. — Production Portfolio',
    title: 'Cinematography case study layout: "Northern Drift" documentary',
    description: 'Editorial layout with side-by-side color grade LUT comparison slider.',
    durationMinutes: 135,
    durationDisplay: '2h15',
    column: 'in_review',
    area: 'Editorial / CSS',
    priority: 'P3',
    energy: 'Low',
    dueDate: 'Fri, Sep 4',
    subtasks: [
      { id: 'sub-131', title: 'Clip-path split slider for Rec.709 vs LOG preview', completed: true },
    ],
  },
  {
    id: 'task-s-client-portal',
    projectId: 'proj-sonder',
    projectName: 'Sonder Film Co. — Production Portfolio',
    title: 'Password protected rough-cut screening link generator',
    description: 'Expiring tokenized links for private producer review with watermark overlay.',
    durationMinutes: 160,
    durationDisplay: '2h40',
    column: 'done',
    area: 'Security',
    priority: 'P1',
    energy: 'Deep',
    dueDate: 'Tue, Sep 1',
    subtasks: [
      { id: 'sub-141', title: 'Generate HMAC signature for video stream URL', completed: true },
    ],
  },
  {
    id: 'task-s-staging-dns',
    projectId: 'proj-sonder',
    projectName: 'Sonder Film Co. — Production Portfolio',
    title: 'Production SSL migration and CDN edge cache invalidation rule',
    description: 'Point apex domain to Cloudflare edge and configure aggressive asset caching for media streams.',
    durationMinutes: 50,
    durationDisplay: '50 min',
    column: 'handoff',
    area: 'DevOps / CDN',
    priority: 'P1',
    energy: 'Low',
    dueDate: 'Mon, Sep 7',
    subtasks: [
      { id: 'sub-151', title: 'Configure cache purge webhook in GitHub Actions', completed: true },
    ],
  },

  // Stillness Board Tasks
  {
    id: 'task-m-binaural',
    projectId: 'proj-stillness',
    projectName: 'Stillness App — Editorial & Audio CMS',
    title: 'Binaural beat oscillator frequency pairing generator',
    description: 'Generate 432Hz theta waves with exact carrier and offset frequencies using Web Audio API nodes.',
    durationMinutes: 160,
    durationDisplay: '2h40',
    column: 'todo',
    area: 'Audio Synthesis',
    priority: 'P1',
    energy: 'Deep',
    dueDate: 'Sat, Sep 6',
    subtasks: [
      { id: 'sub-161', title: 'Calibrate StereoPannerNode channel separation', completed: false },
      { id: 'sub-162', title: 'Add gradual fade-in gain envelope over 12 seconds', completed: false },
    ],
  },
  {
    id: 'task-m-cms',
    projectId: 'proj-stillness',
    projectName: 'Stillness App — Editorial & Audio CMS',
    title: 'Sanity CMS document validation for practitioner credentials',
    description: 'Ensure audio meditation authors have license verification uploaded before session publication.',
    durationMinutes: 70,
    durationDisplay: '1h10',
    column: 'backlog',
    area: 'CMS / Schema',
    priority: 'P3',
    energy: 'Low',
    dueDate: 'Tue, Sep 8',
    subtasks: [
      { id: 'sub-171', title: 'Custom rule builder for PDF validation in desk tool', completed: false },
    ],
  },
  {
    id: 'task-m-breath',
    projectId: 'proj-stillness',
    projectName: 'Stillness App — Editorial & Audio CMS',
    title: '4-7-8 Breathing circle animation spring damping',
    description: 'Tune cubic bezier curves for inhalation expansion and gentle exhalation contract without frame drop.',
    durationMinutes: 65,
    durationDisplay: '1h05',
    column: 'in_review',
    area: 'Motion / SVG',
    priority: 'P2',
    energy: 'Medium',
    dueDate: 'Wed, Sep 3',
    subtasks: [
      { id: 'sub-181', title: 'Test 120Hz ProMotion iPad screen response', completed: true },
    ],
  },
  {
    id: 'task-m-export-hls',
    projectId: 'proj-stillness',
    projectName: 'Stillness App — Editorial & Audio CMS',
    title: 'Automated HLS audio stream transcode pipeline test',
    description: 'Verify 64kbps, 128kbps, and 256kbps AAC audio streams play smoothly over throttled 3G cellular.',
    durationMinutes: 125,
    durationDisplay: '2h05',
    column: 'done',
    area: 'Media / Infra',
    priority: 'P2',
    energy: 'Medium',
    dueDate: 'Sun, Aug 30',
    subtasks: [
      { id: 'sub-191', title: 'Set up ffmpeg segment manifest parser', completed: true },
    ],
  },
  {
    id: 'task-m-client-walkthrough',
    projectId: 'proj-stillness',
    projectName: 'Stillness App — Editorial & Audio CMS',
    title: 'Sanity Studio editor walkthrough with head instructor',
    description: 'Walk Maya through track uploading, tag assignment, and schedule previewing.',
    durationMinutes: 60,
    durationDisplay: '1h00',
    column: 'handoff',
    area: 'Client / Training',
    priority: 'P2',
    energy: 'Medium',
    dueDate: 'Thu, Sep 10',
    subtasks: [
      { id: 'sub-201', title: 'Record 8-minute Loom walkthrough for editorial staff', completed: true },
    ],
  },
];

export const INITIAL_AT_RISK: AtRiskItem[] = [
  {
    id: 'risk-1',
    taskId: 'task-s-scrubber',
    projectName: 'Sonder Film Co.',
    title: 'Custom video playback scrubber with frame accurate hover',
    shortfall: 'needs 4h, 1h30 available before Fri',
    hoursNeeded: 4.0,
    hoursAvailable: 1.5,
    dueDate: 'Fri, 17:00',
  },
  {
    id: 'risk-2',
    taskId: 'task-k-webhook',
    projectName: 'Komorebi Tea',
    title: 'Shopify headless webhook sync & error boundary',
    shortfall: 'needs 3h15, 45 min available before Thu',
    hoursNeeded: 3.25,
    hoursAvailable: 0.75,
    dueDate: 'Thu, 12:00',
  },
  {
    id: 'risk-3',
    taskId: 'task-m-binaural',
    projectName: 'Stillness App',
    title: 'Binaural beat oscillator frequency pairing generator',
    shortfall: 'needs 2h40, 1h10 available before Sat',
    hoursNeeded: 2.67,
    hoursAvailable: 1.17,
    dueDate: 'Sat, 14:00',
  },
];

export const INITIAL_CHAT_MESSAGES: ChatMessage[] = [
  {
    id: 'msg-1',
    sender: 'assistant',
    timestamp: '1:20 pm',
    text: 'You clocked out of your shift at 1:15 pm. Factoring in 45 min for travel and lunch, your freelance window opens at 2:00 pm and closes at 6:30 pm (4h30 available).',
  },
  {
    id: 'msg-2',
    sender: 'assistant',
    timestamp: '1:21 pm',
    text: '4h30 available today after your 1:15 pm shift. Committed tasks total 5h00, leaving a 30-minute deficit.',
    actions: [
      {
        label: 'Shorten WebGL physics task from 47m to 17m (clears deficit)',
        type: 'shorten',
        payload: 'task-s-webgl',
      },
      {
        label: 'Reschedule Audio chunk cache to Saturday afternoon',
        type: 'reschedule',
        payload: 'task-m-audio',
      },
      {
        label: 'Keep 5h00 and extend evening window to 7:00 pm',
        type: 'extend',
        payload: 'window',
      },
    ],
  },
];
